/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_FrenSer_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {20, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {24, 1, 1};
static const casadi_int casadi_s5[51] = 
  {24, 24, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 20, 21, 22, 23, 0,
  1, 2, 3};
static const casadi_int casadi_s6[3] = {24, 0, 1};

/* drone_FrenSer_cost_y_0_fun_jac_ut_xt:(i0[20],i1[4],i2[0],i3[],i4[0])->(o0[24],o1[24x24,24nz],o2[24x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, *w02=w+25, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = input[0][1] */
  w00 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #4: @0 = input[0][2] */
  w00 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #6: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @0 */
  if (res[0]) res[0][3] = w00;
  /* #8: @0 = input[0][4] */
  w00 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][4] = @0 */
  if (res[0]) res[0][4] = w00;
  /* #10: @0 = input[0][5] */
  w00 = arg[0] ? arg[0][5] : 0;
  /* #11: output[0][5] = @0 */
  if (res[0]) res[0][5] = w00;
  /* #12: @0 = input[0][6] */
  w00 = arg[0] ? arg[0][6] : 0;
  /* #13: output[0][6] = @0 */
  if (res[0]) res[0][6] = w00;
  /* #14: @0 = input[0][7] */
  w00 = arg[0] ? arg[0][7] : 0;
  /* #15: output[0][7] = @0 */
  if (res[0]) res[0][7] = w00;
  /* #16: @0 = input[0][8] */
  w00 = arg[0] ? arg[0][8] : 0;
  /* #17: output[0][8] = @0 */
  if (res[0]) res[0][8] = w00;
  /* #18: @0 = input[0][9] */
  w00 = arg[0] ? arg[0][9] : 0;
  /* #19: output[0][9] = @0 */
  if (res[0]) res[0][9] = w00;
  /* #20: @0 = input[0][10] */
  w00 = arg[0] ? arg[0][10] : 0;
  /* #21: output[0][10] = @0 */
  if (res[0]) res[0][10] = w00;
  /* #22: @0 = input[0][11] */
  w00 = arg[0] ? arg[0][11] : 0;
  /* #23: output[0][11] = @0 */
  if (res[0]) res[0][11] = w00;
  /* #24: @0 = input[0][12] */
  w00 = arg[0] ? arg[0][12] : 0;
  /* #25: output[0][12] = @0 */
  if (res[0]) res[0][12] = w00;
  /* #26: @0 = input[0][13] */
  w00 = arg[0] ? arg[0][13] : 0;
  /* #27: output[0][13] = @0 */
  if (res[0]) res[0][13] = w00;
  /* #28: @0 = input[0][14] */
  w00 = arg[0] ? arg[0][14] : 0;
  /* #29: output[0][14] = @0 */
  if (res[0]) res[0][14] = w00;
  /* #30: @0 = input[0][15] */
  w00 = arg[0] ? arg[0][15] : 0;
  /* #31: output[0][15] = @0 */
  if (res[0]) res[0][15] = w00;
  /* #32: @0 = input[0][16] */
  w00 = arg[0] ? arg[0][16] : 0;
  /* #33: output[0][16] = @0 */
  if (res[0]) res[0][16] = w00;
  /* #34: @0 = input[0][17] */
  w00 = arg[0] ? arg[0][17] : 0;
  /* #35: output[0][17] = @0 */
  if (res[0]) res[0][17] = w00;
  /* #36: @0 = input[0][18] */
  w00 = arg[0] ? arg[0][18] : 0;
  /* #37: output[0][18] = @0 */
  if (res[0]) res[0][18] = w00;
  /* #38: @0 = input[0][19] */
  w00 = arg[0] ? arg[0][19] : 0;
  /* #39: output[0][19] = @0 */
  if (res[0]) res[0][19] = w00;
  /* #40: @0 = input[1][0] */
  w00 = arg[1] ? arg[1][0] : 0;
  /* #41: output[0][20] = @0 */
  if (res[0]) res[0][20] = w00;
  /* #42: @0 = input[1][1] */
  w00 = arg[1] ? arg[1][1] : 0;
  /* #43: output[0][21] = @0 */
  if (res[0]) res[0][21] = w00;
  /* #44: @0 = input[1][2] */
  w00 = arg[1] ? arg[1][2] : 0;
  /* #45: output[0][22] = @0 */
  if (res[0]) res[0][22] = w00;
  /* #46: @0 = input[1][3] */
  w00 = arg[1] ? arg[1][3] : 0;
  /* #47: output[0][23] = @0 */
  if (res[0]) res[0][23] = w00;
  /* #48: @1 = zeros(24x24,24nz) */
  casadi_clear(w01, 24);
  /* #49: @2 = ones(24x1) */
  casadi_fill(w02, 24, 1.);
  /* #50: {@0, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25} = vertsplit(@2) */
  w00 = w02[0];
  w03 = w02[1];
  w04 = w02[2];
  w05 = w02[3];
  w06 = w02[4];
  w07 = w02[5];
  w08 = w02[6];
  w09 = w02[7];
  w10 = w02[8];
  w11 = w02[9];
  w12 = w02[10];
  w13 = w02[11];
  w14 = w02[12];
  w15 = w02[13];
  w16 = w02[14];
  w17 = w02[15];
  w18 = w02[16];
  w19 = w02[17];
  w20 = w02[18];
  w21 = w02[19];
  w22 = w02[20];
  w23 = w02[21];
  w24 = w02[22];
  w25 = w02[23];
  /* #51: @2 = vertcat(@6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @0, @3, @4, @5) */
  rr=w02;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w00;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  /* #52: (@1[:24] = @2) */
  for (rr=w01+0, cs=w02; rr!=w01+24; rr+=1) *rr = *cs++;
  /* #53: output[1][0] = @1 */
  casadi_copy(w01, 24, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_FrenSer_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_FrenSer_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int drone_FrenSer_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real drone_FrenSer_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_FrenSer_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_FrenSer_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_FrenSer_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_FrenSer_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 29;
  if (sz_res) *sz_res = 27;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 72;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_FrenSer_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 29*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 27*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 72*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
