/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) morphocopter_model_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[13] = 
  {1, 5, 0, 1, 2, 3, 4, 5,
  0, 0, 0, 0, 0};
static const casadi_int casadi_s1[33] = 
  {5, 5, 0, 5, 10, 15, 20, 25,
  0, 1, 2, 3, 4, 0, 1, 2,
  3, 4, 0, 1, 2, 3, 4, 0,
  1, 2, 3, 4, 0, 1, 2, 3,
  4};
static const casadi_int casadi_s2[9] = 
  {1, 5, 0, 1, 1, 1, 1, 1,
  0};
static const casadi_int casadi_s3[5] = {0, 1, 2, 8, 12};
static const casadi_int casadi_s4[9] = 
  {1, 5, 0, 0, 1, 1, 1, 1,
  0};
static const casadi_int casadi_s5[9] = 
  {1, 5, 0, 0, 0, 1, 1, 1,
  0};
static const casadi_int casadi_s6[9] = 
  {1, 5, 0, 0, 0, 0, 1, 1,
  0};
static const casadi_int casadi_s7[9] = 
  {1, 5, 0, 0, 0, 0, 0, 1,
  0};
static const casadi_int casadi_s8[42] = 
  {14, 14, 0, 5, 10, 15, 15, 15,
  15, 15, 15, 20, 20, 20, 20, 25,
  25, 0, 1, 2, 8, 12, 0, 1,
  2, 8, 12, 0, 1, 2, 8, 12,
  0, 1, 2, 8, 12, 0, 1, 2,
  8, 12};
static const casadi_int casadi_s9[3] = {14, 1, 1};
static const casadi_int casadi_s10[3] = {0, 1, 1};
static const casadi_int casadi_s11[3] = {124, 1, 1};
static const casadi_int casadi_s12[3] = {1, 1, 1};
static const casadi_int casadi_s13[3] = {0, 0, 1};
static const casadi_int casadi_s14[3] = {0, 14, 1};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* morphocopter_model_cost_ext_cost_e_fun_jac_hess:(i0[14],i1[0],i2[0],i3[124])->(o0,o1[14],o2[14x14,25nz],o3[],o4[0x14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+3, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+22, *w18=w+36, *w19=w+39, *w20=w+44, *w21=w+54, *w22=w+59;
  casadi_real *w24=w+171, *w25=w+196, *w26=w+201, *w27=w+226, w28, *w29=w+241;
  const casadi_int *cii;
  const casadi_real *cs, *ct, *wr20, *wr21, *wr23;
  /* #0: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x5) */
  casadi_clear(w02, 5);
  /* #3: @3 = input[0][0] */
  w03 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #5: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #6: @6 = input[0][3] */
  w06 = arg[0] ? arg[0][3] : 0;
  /* #7: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #8: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #9: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][6] : 0;
  /* #10: @10 = input[0][7] */
  w10 = arg[0] ? arg[0][7] : 0;
  /* #11: @11 = input[0][8] */
  w11 = arg[0] ? arg[0][8] : 0;
  /* #12: @12 = input[0][9] */
  w12 = arg[0] ? arg[0][9] : 0;
  /* #13: @13 = input[0][10] */
  w13 = arg[0] ? arg[0][10] : 0;
  /* #14: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #15: @15 = input[0][12] */
  w15 = arg[0] ? arg[0][12] : 0;
  /* #16: @16 = input[0][13] */
  w16 = arg[0] ? arg[0][13] : 0;
  /* #17: @17 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @19 = vertcat(@18, @11, @15) */
  rr=w19;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  *rr++ = w11;
  *rr++ = w15;
  /* #20: @20 = input[3][1] */
  wr20 = arg[3] ? arg[3]+102 : casadi_zeros;
  /* #21: @21 = @20[:5] */
  wr21 = wr20+0;
  /* #22: @19 = (@19-@21) */
  for (i=0, rr=w19, cs=wr21; i<5; ++i) (*rr++) -= (*cs++);
  /* #23: @21 = @19' */
  casadi_copy(w19, 5, w21);
  /* #24: @22 = zeros(10x10) */
  casadi_clear(w22, 100);
  /* #25: @23 = input[3][2] */
  wr23 = arg[3] ? arg[3]+112 : casadi_zeros;
  /* #26: @11 = @23[0] */
  w11 = wr23[0];
  /* #27: (@22[0] = @11) */
  for (rr=w22+0, cs=(&w11); rr!=w22+1; rr+=1) *rr = *cs++;
  /* #28: @11 = @23[1] */
  w11 = wr23[1];
  /* #29: (@22[11] = @11) */
  for (rr=w22+11, cs=(&w11); rr!=w22+12; rr+=1) *rr = *cs++;
  /* #30: @11 = @23[2] */
  w11 = wr23[2];
  /* #31: (@22[22] = @11) */
  for (rr=w22+22, cs=(&w11); rr!=w22+23; rr+=1) *rr = *cs++;
  /* #32: @11 = @23[3] */
  w11 = wr23[3];
  /* #33: (@22[33] = @11) */
  for (rr=w22+33, cs=(&w11); rr!=w22+34; rr+=1) *rr = *cs++;
  /* #34: @11 = @23[4] */
  w11 = wr23[4];
  /* #35: (@22[44] = @11) */
  for (rr=w22+44, cs=(&w11); rr!=w22+45; rr+=1) *rr = *cs++;
  /* #36: @11 = @23[5] */
  w11 = wr23[5];
  /* #37: (@22[55] = @11) */
  for (rr=w22+55, cs=(&w11); rr!=w22+56; rr+=1) *rr = *cs++;
  /* #38: @11 = @23[6] */
  w11 = wr23[6];
  /* #39: (@22[66] = @11) */
  for (rr=w22+66, cs=(&w11); rr!=w22+67; rr+=1) *rr = *cs++;
  /* #40: @11 = @23[7] */
  w11 = wr23[7];
  /* #41: (@22[77] = @11) */
  for (rr=w22+77, cs=(&w11); rr!=w22+78; rr+=1) *rr = *cs++;
  /* #42: @11 = @23[8] */
  w11 = wr23[8];
  /* #43: (@22[88] = @11) */
  for (rr=w22+88, cs=(&w11); rr!=w22+89; rr+=1) *rr = *cs++;
  /* #44: @11 = @23[9] */
  w11 = wr23[9];
  /* #45: (@22[99] = @11) */
  for (rr=w22+99, cs=(&w11); rr!=w22+100; rr+=1) *rr = *cs++;
  /* #46: @11 = @23[10] */
  w11 = wr23[10];
  /* #47: (@22[10] = @11) */
  for (rr=w22+10, cs=(&w11); rr!=w22+11; rr+=1) *rr = *cs++;
  /* #48: @11 = @23[11] */
  w11 = wr23[11];
  /* #49: (@22[1] = @11) */
  for (rr=w22+1, cs=(&w11); rr!=w22+2; rr+=1) *rr = *cs++;
  /* #50: @24 = @22[:50:10;:5] */
  for (rr=w24, cs=w22+0; cs!=w22+50; cs+=10) for (ct=cs+0; ct!=cs+5; ct+=1) *rr++ = *ct;
  /* #51: @25 = mac(@21,@24,@2) */
  casadi_copy(w02, 5, w25);
  for (i=0, rr=w25; i<5; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w24+i*5; k<5; ++k) *rr += cs[k*1]**ct++;
  /* #52: @1 = mac(@25,@19,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w19+i*5; k<5; ++k) *rr += cs[k*1]**ct++;
  /* #53: @1 = (@0*@1) */
  w01  = (w00*w01);
  /* #54: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #55: @17 = zeros(14x1) */
  casadi_clear(w17, 14);
  /* #56: @25 = @25' */
  /* #57: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #58: @21 = (@0*@21) */
  for (i=0, rr=w21, cs=w21; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #59: @26 = @24' */
  for (i=0, rr=w26, cs=w24; i<5; ++i) for (j=0; j<5; ++j) rr[i+j*5] = *cs++;
  /* #60: @19 = mac(@21,@26,@2) */
  casadi_copy(w02, 5, w19);
  for (i=0, rr=w19; i<5; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w26+i*5; k<5; ++k) *rr += cs[k*1]**ct++;
  /* #61: @19 = @19' */
  /* #62: @25 = (@25+@19) */
  for (i=0, rr=w25, cs=w19; i<5; ++i) (*rr++) += (*cs++);
  /* #63: {@18, @1, @11} = vertsplit(@25) */
  casadi_copy(w25, 3, w18);
  w01 = w25[3];
  w11 = w25[4];
  /* #64: @27 = @17; (@27[:3] += @18) */
  casadi_copy(w17, 14, w27);
  for (rr=w27+0, cs=w18; rr!=w27+3; rr+=1) *rr += *cs++;
  /* #65: {@15, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @16, @28} = vertsplit(@27) */
  w15 = w27[0];
  w03 = w27[1];
  w04 = w27[2];
  w05 = w27[3];
  w06 = w27[4];
  w07 = w27[5];
  w08 = w27[6];
  w09 = w27[7];
  w10 = w27[8];
  w12 = w27[9];
  w13 = w27[10];
  w14 = w27[11];
  w16 = w27[12];
  w28 = w27[13];
  /* #66: output[1][0] = @15 */
  if (res[1]) res[1][0] = w15;
  /* #67: output[1][1] = @3 */
  if (res[1]) res[1][1] = w03;
  /* #68: output[1][2] = @4 */
  if (res[1]) res[1][2] = w04;
  /* #69: output[1][3] = @5 */
  if (res[1]) res[1][3] = w05;
  /* #70: output[1][4] = @6 */
  if (res[1]) res[1][4] = w06;
  /* #71: output[1][5] = @7 */
  if (res[1]) res[1][5] = w07;
  /* #72: output[1][6] = @8 */
  if (res[1]) res[1][6] = w08;
  /* #73: output[1][7] = @9 */
  if (res[1]) res[1][7] = w09;
  /* #74: @1 = (@1+@10) */
  w01 += w10;
  /* #75: output[1][8] = @1 */
  if (res[1]) res[1][8] = w01;
  /* #76: output[1][9] = @12 */
  if (res[1]) res[1][9] = w12;
  /* #77: output[1][10] = @13 */
  if (res[1]) res[1][10] = w13;
  /* #78: output[1][11] = @14 */
  if (res[1]) res[1][11] = w14;
  /* #79: @11 = (@11+@16) */
  w11 += w16;
  /* #80: output[1][12] = @11 */
  if (res[1]) res[1][12] = w11;
  /* #81: output[1][13] = @28 */
  if (res[1]) res[1][13] = w28;
  /* #82: @29 = zeros(14x14,25nz) */
  casadi_clear(w29, 25);
  /* #83: @20 = ones(14x1,10nz) */
  casadi_fill(w20, 10, 1.);
  /* #84: {@28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@20) */
  w28 = w20[0];
  /* #85: @28 = sparsity_cast(@28) */
  /* #86: @30 = 00 */
  /* #87: @11 = vertcat(@28, @30, @30) */
  rr=(&w11);
  *rr++ = w28;
  /* #88: @11 = @11' */
  /* #89: @25 = mac(@11,@24,@2) */
  casadi_copy(w02, 5, w25);
  casadi_mtimes((&w11), casadi_s2, w24, casadi_s1, w25, casadi_s0, w, 0);
  /* #90: @25 = @25' */
  /* #91: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #92: @11 = (@0*@11) */
  w11  = (w00*w11);
  /* #93: @19 = mac(@11,@26,@2) */
  casadi_copy(w02, 5, w19);
  casadi_mtimes((&w11), casadi_s2, w26, casadi_s1, w19, casadi_s0, w, 0);
  /* #94: @19 = @19' */
  /* #95: @25 = (@25+@19) */
  for (i=0, rr=w25, cs=w19; i<5; ++i) (*rr++) += (*cs++);
  /* #96: {@18, @11, @28} = vertsplit(@25) */
  casadi_copy(w25, 3, w18);
  w11 = w25[3];
  w28 = w25[4];
  /* #97: @27 = @17; (@27[:3] += @18) */
  casadi_copy(w17, 14, w27);
  for (rr=w27+0, cs=w18; rr!=w27+3; rr+=1) *rr += *cs++;
  /* #98: {@16, @14, @13, @12, @1, @10, @9, @8, @7, @6, @5, @4, @3, @15} = vertsplit(@27) */
  w16 = w27[0];
  w14 = w27[1];
  w13 = w27[2];
  w12 = w27[3];
  w01 = w27[4];
  w10 = w27[5];
  w09 = w27[6];
  w08 = w27[7];
  w07 = w27[8];
  w06 = w27[9];
  w05 = w27[10];
  w04 = w27[11];
  w03 = w27[12];
  w15 = w27[13];
  /* #99: @11 = (@11+@7) */
  w11 += w07;
  /* #100: @28 = (@28+@3) */
  w28 += w03;
  /* #101: @27 = vertcat(@16, @14, @13, @12, @1, @10, @9, @8, @11, @6, @5, @4, @28, @15) */
  rr=w27;
  *rr++ = w16;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w01;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w04;
  *rr++ = w28;
  *rr++ = w15;
  /* #102: @25 = @27[0, 1, 2, 8, 12] */
  for (cii=casadi_s3, rr=w25, cs=w27; cii!=casadi_s3+5; ++cii) *rr++ = cs[*cii];
  /* #103: (@29[:5] = @25) */
  for (rr=w29+0, cs=w25; rr!=w29+5; rr+=1) *rr = *cs++;
  /* #104: (@29[:25:5] = @25) */
  for (rr=w29+0, cs=w25; rr!=w29+25; rr+=5) *rr = *cs++;
  /* #105: @16 = ones(14x1,1nz) */
  w16 = 1.;
  /* #106: {NULL, @14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@16) */
  w14 = w16;
  /* #107: @14 = sparsity_cast(@14) */
  /* #108: @16 = vertcat(@14, @30, @30) */
  rr=(&w16);
  *rr++ = w14;
  /* #109: @16 = @16' */
  /* #110: @25 = mac(@16,@24,@2) */
  casadi_copy(w02, 5, w25);
  casadi_mtimes((&w16), casadi_s4, w24, casadi_s1, w25, casadi_s0, w, 0);
  /* #111: @25 = @25' */
  /* #112: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #113: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #114: @19 = mac(@16,@26,@2) */
  casadi_copy(w02, 5, w19);
  casadi_mtimes((&w16), casadi_s4, w26, casadi_s1, w19, casadi_s0, w, 0);
  /* #115: @19 = @19' */
  /* #116: @25 = (@25+@19) */
  for (i=0, rr=w25, cs=w19; i<5; ++i) (*rr++) += (*cs++);
  /* #117: {@18, @16, @14} = vertsplit(@25) */
  casadi_copy(w25, 3, w18);
  w16 = w25[3];
  w14 = w25[4];
  /* #118: @27 = @17; (@27[:3] += @18) */
  casadi_copy(w17, 14, w27);
  for (rr=w27+0, cs=w18; rr!=w27+3; rr+=1) *rr += *cs++;
  /* #119: {@13, @12, @1, @10, @9, @8, @11, @6, @5, @4, @28, @15, @3, @7} = vertsplit(@27) */
  w13 = w27[0];
  w12 = w27[1];
  w01 = w27[2];
  w10 = w27[3];
  w09 = w27[4];
  w08 = w27[5];
  w11 = w27[6];
  w06 = w27[7];
  w05 = w27[8];
  w04 = w27[9];
  w28 = w27[10];
  w15 = w27[11];
  w03 = w27[12];
  w07 = w27[13];
  /* #120: @16 = (@16+@5) */
  w16 += w05;
  /* #121: @14 = (@14+@3) */
  w14 += w03;
  /* #122: @27 = vertcat(@13, @12, @1, @10, @9, @8, @11, @6, @16, @4, @28, @15, @14, @7) */
  rr=w27;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w01;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w16;
  *rr++ = w04;
  *rr++ = w28;
  *rr++ = w15;
  *rr++ = w14;
  *rr++ = w07;
  /* #123: @25 = @27[0, 1, 2, 8, 12] */
  for (cii=casadi_s3, rr=w25, cs=w27; cii!=casadi_s3+5; ++cii) *rr++ = cs[*cii];
  /* #124: (@29[5:10] = @25) */
  for (rr=w29+5, cs=w25; rr!=w29+10; rr+=1) *rr = *cs++;
  /* #125: (@29[1:26:5] = @25) */
  for (rr=w29+1, cs=w25; rr!=w29+26; rr+=5) *rr = *cs++;
  /* #126: @13 = ones(14x1,1nz) */
  w13 = 1.;
  /* #127: {NULL, NULL, @12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@13) */
  w12 = w13;
  /* #128: @12 = sparsity_cast(@12) */
  /* #129: @13 = vertcat(@12, @30, @30) */
  rr=(&w13);
  *rr++ = w12;
  /* #130: @13 = @13' */
  /* #131: @25 = mac(@13,@24,@2) */
  casadi_copy(w02, 5, w25);
  casadi_mtimes((&w13), casadi_s5, w24, casadi_s1, w25, casadi_s0, w, 0);
  /* #132: @25 = @25' */
  /* #133: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #134: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #135: @19 = mac(@13,@26,@2) */
  casadi_copy(w02, 5, w19);
  casadi_mtimes((&w13), casadi_s5, w26, casadi_s1, w19, casadi_s0, w, 0);
  /* #136: @19 = @19' */
  /* #137: @25 = (@25+@19) */
  for (i=0, rr=w25, cs=w19; i<5; ++i) (*rr++) += (*cs++);
  /* #138: {@18, @13, @12} = vertsplit(@25) */
  casadi_copy(w25, 3, w18);
  w13 = w25[3];
  w12 = w25[4];
  /* #139: @27 = @17; (@27[:3] += @18) */
  casadi_copy(w17, 14, w27);
  for (rr=w27+0, cs=w18; rr!=w27+3; rr+=1) *rr += *cs++;
  /* #140: {@1, @10, @9, @8, @11, @6, @16, @4, @28, @15, @14, @7, @3, @5} = vertsplit(@27) */
  w01 = w27[0];
  w10 = w27[1];
  w09 = w27[2];
  w08 = w27[3];
  w11 = w27[4];
  w06 = w27[5];
  w16 = w27[6];
  w04 = w27[7];
  w28 = w27[8];
  w15 = w27[9];
  w14 = w27[10];
  w07 = w27[11];
  w03 = w27[12];
  w05 = w27[13];
  /* #141: @13 = (@13+@28) */
  w13 += w28;
  /* #142: @12 = (@12+@3) */
  w12 += w03;
  /* #143: @27 = vertcat(@1, @10, @9, @8, @11, @6, @16, @4, @13, @15, @14, @7, @12, @5) */
  rr=w27;
  *rr++ = w01;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w16;
  *rr++ = w04;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w14;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w05;
  /* #144: @25 = @27[0, 1, 2, 8, 12] */
  for (cii=casadi_s3, rr=w25, cs=w27; cii!=casadi_s3+5; ++cii) *rr++ = cs[*cii];
  /* #145: (@29[10:15] = @25) */
  for (rr=w29+10, cs=w25; rr!=w29+15; rr+=1) *rr = *cs++;
  /* #146: (@29[2:27:5] = @25) */
  for (rr=w29+2, cs=w25; rr!=w29+27; rr+=5) *rr = *cs++;
  /* #147: @31 = zeros(3x1,0nz) */
  /* #148: @1 = ones(14x1,1nz) */
  w01 = 1.;
  /* #149: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL, NULL} = vertsplit(@1) */
  w10 = w01;
  /* #150: @1 = vertcat(@31, @10, @30) */
  rr=(&w01);
  *rr++ = w10;
  /* #151: @1 = @1' */
  /* #152: @25 = mac(@1,@24,@2) */
  casadi_copy(w02, 5, w25);
  casadi_mtimes((&w01), casadi_s6, w24, casadi_s1, w25, casadi_s0, w, 0);
  /* #153: @25 = @25' */
  /* #154: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #155: @1 = (@0*@1) */
  w01  = (w00*w01);
  /* #156: @19 = mac(@1,@26,@2) */
  casadi_copy(w02, 5, w19);
  casadi_mtimes((&w01), casadi_s6, w26, casadi_s1, w19, casadi_s0, w, 0);
  /* #157: @19 = @19' */
  /* #158: @25 = (@25+@19) */
  for (i=0, rr=w25, cs=w19; i<5; ++i) (*rr++) += (*cs++);
  /* #159: {@18, @1, @10} = vertsplit(@25) */
  casadi_copy(w25, 3, w18);
  w01 = w25[3];
  w10 = w25[4];
  /* #160: @27 = @17; (@27[:3] += @18) */
  casadi_copy(w17, 14, w27);
  for (rr=w27+0, cs=w18; rr!=w27+3; rr+=1) *rr += *cs++;
  /* #161: {@9, @8, @11, @6, @16, @4, @13, @15, @14, @7, @12, @5, @3, @28} = vertsplit(@27) */
  w09 = w27[0];
  w08 = w27[1];
  w11 = w27[2];
  w06 = w27[3];
  w16 = w27[4];
  w04 = w27[5];
  w13 = w27[6];
  w15 = w27[7];
  w14 = w27[8];
  w07 = w27[9];
  w12 = w27[10];
  w05 = w27[11];
  w03 = w27[12];
  w28 = w27[13];
  /* #162: @1 = (@1+@14) */
  w01 += w14;
  /* #163: @10 = (@10+@3) */
  w10 += w03;
  /* #164: @27 = vertcat(@9, @8, @11, @6, @16, @4, @13, @15, @1, @7, @12, @5, @10, @28) */
  rr=w27;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w16;
  *rr++ = w04;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w01;
  *rr++ = w07;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w10;
  *rr++ = w28;
  /* #165: @25 = @27[0, 1, 2, 8, 12] */
  for (cii=casadi_s3, rr=w25, cs=w27; cii!=casadi_s3+5; ++cii) *rr++ = cs[*cii];
  /* #166: (@29[15:20] = @25) */
  for (rr=w29+15, cs=w25; rr!=w29+20; rr+=1) *rr = *cs++;
  /* #167: (@29[3:28:5] = @25) */
  for (rr=w29+3, cs=w25; rr!=w29+28; rr+=5) *rr = *cs++;
  /* #168: @9 = ones(14x1,1nz) */
  w09 = 1.;
  /* #169: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @8, NULL} = vertsplit(@9) */
  w08 = w09;
  /* #170: @9 = vertcat(@31, @30, @8) */
  rr=(&w09);
  *rr++ = w08;
  /* #171: @9 = @9' */
  /* #172: @25 = mac(@9,@24,@2) */
  casadi_copy(w02, 5, w25);
  casadi_mtimes((&w09), casadi_s7, w24, casadi_s1, w25, casadi_s0, w, 0);
  /* #173: @25 = @25' */
  /* #174: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #175: @0 = (@0*@9) */
  w00 *= w09;
  /* #176: @2 = mac(@0,@26,@2) */
  casadi_mtimes((&w00), casadi_s7, w26, casadi_s1, w02, casadi_s0, w, 0);
  /* #177: @2 = @2' */
  /* #178: @25 = (@25+@2) */
  for (i=0, rr=w25, cs=w02; i<5; ++i) (*rr++) += (*cs++);
  /* #179: {@18, @0, @9} = vertsplit(@25) */
  casadi_copy(w25, 3, w18);
  w00 = w25[3];
  w09 = w25[4];
  /* #180: (@17[:3] += @18) */
  for (rr=w17+0, cs=w18; rr!=w17+3; rr+=1) *rr += *cs++;
  /* #181: {@8, @11, @6, @16, @4, @13, @15, @1, @7, @12, @5, @10, @28, @3} = vertsplit(@17) */
  w08 = w17[0];
  w11 = w17[1];
  w06 = w17[2];
  w16 = w17[3];
  w04 = w17[4];
  w13 = w17[5];
  w15 = w17[6];
  w01 = w17[7];
  w07 = w17[8];
  w12 = w17[9];
  w05 = w17[10];
  w10 = w17[11];
  w28 = w17[12];
  w03 = w17[13];
  /* #182: @0 = (@0+@7) */
  w00 += w07;
  /* #183: @9 = (@9+@28) */
  w09 += w28;
  /* #184: @17 = vertcat(@8, @11, @6, @16, @4, @13, @15, @1, @0, @12, @5, @10, @9, @3) */
  rr=w17;
  *rr++ = w08;
  *rr++ = w11;
  *rr++ = w06;
  *rr++ = w16;
  *rr++ = w04;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w01;
  *rr++ = w00;
  *rr++ = w12;
  *rr++ = w05;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w03;
  /* #185: @25 = @17[0, 1, 2, 8, 12] */
  for (cii=casadi_s3, rr=w25, cs=w17; cii!=casadi_s3+5; ++cii) *rr++ = cs[*cii];
  /* #186: (@29[20:25] = @25) */
  for (rr=w29+20, cs=w25; rr!=w29+25; rr+=1) *rr = *cs++;
  /* #187: (@29[4:29:5] = @25) */
  for (rr=w29+4, cs=w25; rr!=w29+29; rr+=5) *rr = *cs++;
  /* #188: @26 = @29' */
  casadi_trans(w29,casadi_s8, w26, casadi_s8, iw);
  /* #189: output[2][0] = @26 */
  casadi_copy(w26, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real morphocopter_model_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s10;
    case 3: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s9;
    case 2: return casadi_s8;
    case 3: return casadi_s13;
    case 4: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 19;
  if (sz_iw) *sz_iw = 15;
  if (sz_w) *sz_w = 266;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 19*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 15*sizeof(casadi_int);
  if (sz_w) *sz_w = 266*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
