/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) morphocopter_model_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {80, 1, 1};
static const casadi_int casadi_s5[3] = {10, 1, 1};
static const casadi_int casadi_s6[23] = 
  {19, 10, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 5, 6, 7,
  13, 17, 0, 1, 2, 3, 4};
static const casadi_int casadi_s7[3] = {10, 0, 1};

/* morphocopter_model_cost_y_0_fun_jac_ut_xt:(i0[14],i1[5],i2[0],i3[],i4[80])->(o0[10],o1[19x10,10nz],o2[10x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, *w14=w+14, *w15=w+28, *w16=w+31, *w17=w+41, w18, w19, w20, w21, w22;
  casadi_real *w23=w+65;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w03 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w04 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w05 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[0][6] */
  w06 = arg[0] ? arg[0][6] : 0;
  /* #7: @7 = input[0][7] */
  w07 = arg[0] ? arg[0][7] : 0;
  /* #8: @8 = input[0][8] */
  w08 = arg[0] ? arg[0][8] : 0;
  /* #9: @9 = input[0][9] */
  w09 = arg[0] ? arg[0][9] : 0;
  /* #10: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #11: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #12: @12 = input[0][12] */
  w12 = arg[0] ? arg[0][12] : 0;
  /* #13: @13 = input[0][13] */
  w13 = arg[0] ? arg[0][13] : 0;
  /* #14: @14 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @15 = @14[:3] */
  for (rr=w15, cs=w14+0; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #16: output[0][0] = @15 */
  casadi_copy(w15, 3, res[0]);
  /* #17: output[0][1] = @8 */
  if (res[0]) res[0][3] = w08;
  /* #18: output[0][2] = @12 */
  if (res[0]) res[0][4] = w12;
  /* #19: @12 = input[1][0] */
  w12 = arg[1] ? arg[1][0] : 0;
  /* #20: output[0][3] = @12 */
  if (res[0]) res[0][5] = w12;
  /* #21: @12 = input[1][1] */
  w12 = arg[1] ? arg[1][1] : 0;
  /* #22: output[0][4] = @12 */
  if (res[0]) res[0][6] = w12;
  /* #23: @12 = input[1][2] */
  w12 = arg[1] ? arg[1][2] : 0;
  /* #24: output[0][5] = @12 */
  if (res[0]) res[0][7] = w12;
  /* #25: @12 = input[1][3] */
  w12 = arg[1] ? arg[1][3] : 0;
  /* #26: output[0][6] = @12 */
  if (res[0]) res[0][8] = w12;
  /* #27: @12 = input[1][4] */
  w12 = arg[1] ? arg[1][4] : 0;
  /* #28: output[0][7] = @12 */
  if (res[0]) res[0][9] = w12;
  /* #29: @16 = zeros(19x10,10nz) */
  casadi_clear(w16, 10);
  /* #30: @17 = ones(19x1) */
  casadi_fill(w17, 19, 1.);
  /* #31: {@12, @8, @0, @1, @2, @3, @4, @5, @6, @7, @9, @10, @11, @13, @18, @19, @20, @21, @22} = vertsplit(@17) */
  w12 = w17[0];
  w08 = w17[1];
  w00 = w17[2];
  w01 = w17[3];
  w02 = w17[4];
  w03 = w17[5];
  w04 = w17[6];
  w05 = w17[7];
  w06 = w17[8];
  w07 = w17[9];
  w09 = w17[10];
  w10 = w17[11];
  w11 = w17[12];
  w13 = w17[13];
  w18 = w17[14];
  w19 = w17[15];
  w20 = w17[16];
  w21 = w17[17];
  w22 = w17[18];
  /* #32: @14 = vertcat(@3, @4, @5, @6, @7, @9, @10, @11, @13, @18, @19, @20, @21, @22) */
  rr=w14;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  /* #33: @15 = @14[:3] */
  for (rr=w15, cs=w14+0; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #34: @23 = vertcat(@15, @13, @21, @12, @8, @0, @1, @2) */
  rr=w23;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  *rr++ = w13;
  *rr++ = w21;
  *rr++ = w12;
  *rr++ = w08;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  /* #35: (@16[:10] = @23) */
  for (rr=w16+0, cs=w23; rr!=w16+10; rr+=1) *rr = *cs++;
  /* #36: output[1][0] = @16 */
  casadi_copy(w16, 10, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real morphocopter_model_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 75;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 22*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 75*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
