/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) morphocopter_model_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {124, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* morphocopter_model_cost_ext_cost_e_fun_jac:(i0[14],i1[0],i2[0],i3[124])->(o0,o1[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+3, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+22, *w18=w+36, *w19=w+39, *w21=w+54, *w22=w+59, *w24=w+171;
  casadi_real *w25=w+196, *w26=w+201;
  const casadi_real *cs, *ct, *wr20, *wr21, *wr23;
  /* #0: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x5) */
  casadi_clear(w02, 5);
  /* #3: @3 = input[0][0] */
  w03 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #5: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #6: @6 = input[0][3] */
  w06 = arg[0] ? arg[0][3] : 0;
  /* #7: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #8: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #9: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][6] : 0;
  /* #10: @10 = input[0][7] */
  w10 = arg[0] ? arg[0][7] : 0;
  /* #11: @11 = input[0][8] */
  w11 = arg[0] ? arg[0][8] : 0;
  /* #12: @12 = input[0][9] */
  w12 = arg[0] ? arg[0][9] : 0;
  /* #13: @13 = input[0][10] */
  w13 = arg[0] ? arg[0][10] : 0;
  /* #14: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #15: @15 = input[0][12] */
  w15 = arg[0] ? arg[0][12] : 0;
  /* #16: @16 = input[0][13] */
  w16 = arg[0] ? arg[0][13] : 0;
  /* #17: @17 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @19 = vertcat(@18, @11, @15) */
  rr=w19;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  *rr++ = w11;
  *rr++ = w15;
  /* #20: @20 = input[3][1] */
  wr20 = arg[3] ? arg[3]+102 : casadi_zeros;
  /* #21: @21 = @20[:5] */
  wr21 = wr20+0;
  /* #22: @19 = (@19-@21) */
  for (i=0, rr=w19, cs=wr21; i<5; ++i) (*rr++) -= (*cs++);
  /* #23: @21 = @19' */
  casadi_copy(w19, 5, w21);
  /* #24: @22 = zeros(10x10) */
  casadi_clear(w22, 100);
  /* #25: @23 = input[3][2] */
  wr23 = arg[3] ? arg[3]+112 : casadi_zeros;
  /* #26: @11 = @23[0] */
  w11 = wr23[0];
  /* #27: (@22[0] = @11) */
  for (rr=w22+0, cs=(&w11); rr!=w22+1; rr+=1) *rr = *cs++;
  /* #28: @11 = @23[1] */
  w11 = wr23[1];
  /* #29: (@22[11] = @11) */
  for (rr=w22+11, cs=(&w11); rr!=w22+12; rr+=1) *rr = *cs++;
  /* #30: @11 = @23[2] */
  w11 = wr23[2];
  /* #31: (@22[22] = @11) */
  for (rr=w22+22, cs=(&w11); rr!=w22+23; rr+=1) *rr = *cs++;
  /* #32: @11 = @23[3] */
  w11 = wr23[3];
  /* #33: (@22[33] = @11) */
  for (rr=w22+33, cs=(&w11); rr!=w22+34; rr+=1) *rr = *cs++;
  /* #34: @11 = @23[4] */
  w11 = wr23[4];
  /* #35: (@22[44] = @11) */
  for (rr=w22+44, cs=(&w11); rr!=w22+45; rr+=1) *rr = *cs++;
  /* #36: @11 = @23[5] */
  w11 = wr23[5];
  /* #37: (@22[55] = @11) */
  for (rr=w22+55, cs=(&w11); rr!=w22+56; rr+=1) *rr = *cs++;
  /* #38: @11 = @23[6] */
  w11 = wr23[6];
  /* #39: (@22[66] = @11) */
  for (rr=w22+66, cs=(&w11); rr!=w22+67; rr+=1) *rr = *cs++;
  /* #40: @11 = @23[7] */
  w11 = wr23[7];
  /* #41: (@22[77] = @11) */
  for (rr=w22+77, cs=(&w11); rr!=w22+78; rr+=1) *rr = *cs++;
  /* #42: @11 = @23[8] */
  w11 = wr23[8];
  /* #43: (@22[88] = @11) */
  for (rr=w22+88, cs=(&w11); rr!=w22+89; rr+=1) *rr = *cs++;
  /* #44: @11 = @23[9] */
  w11 = wr23[9];
  /* #45: (@22[99] = @11) */
  for (rr=w22+99, cs=(&w11); rr!=w22+100; rr+=1) *rr = *cs++;
  /* #46: @11 = @23[10] */
  w11 = wr23[10];
  /* #47: (@22[10] = @11) */
  for (rr=w22+10, cs=(&w11); rr!=w22+11; rr+=1) *rr = *cs++;
  /* #48: @11 = @23[11] */
  w11 = wr23[11];
  /* #49: (@22[1] = @11) */
  for (rr=w22+1, cs=(&w11); rr!=w22+2; rr+=1) *rr = *cs++;
  /* #50: @24 = @22[:50:10;:5] */
  for (rr=w24, cs=w22+0; cs!=w22+50; cs+=10) for (ct=cs+0; ct!=cs+5; ct+=1) *rr++ = *ct;
  /* #51: @25 = mac(@21,@24,@2) */
  casadi_copy(w02, 5, w25);
  for (i=0, rr=w25; i<5; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w24+i*5; k<5; ++k) *rr += cs[k*1]**ct++;
  /* #52: @1 = mac(@25,@19,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w25+j, ct=w19+i*5; k<5; ++k) *rr += cs[k*1]**ct++;
  /* #53: @1 = (@0*@1) */
  w01  = (w00*w01);
  /* #54: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #55: @17 = zeros(14x1) */
  casadi_clear(w17, 14);
  /* #56: @25 = @25' */
  /* #57: @25 = (@0*@25) */
  for (i=0, rr=w25, cs=w25; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #58: @21 = (@0*@21) */
  for (i=0, rr=w21, cs=w21; i<5; ++i) (*rr++)  = (w00*(*cs++));
  /* #59: @26 = @24' */
  for (i=0, rr=w26, cs=w24; i<5; ++i) for (j=0; j<5; ++j) rr[i+j*5] = *cs++;
  /* #60: @2 = mac(@21,@26,@2) */
  for (i=0, rr=w02; i<5; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w26+i*5; k<5; ++k) *rr += cs[k*1]**ct++;
  /* #61: @2 = @2' */
  /* #62: @25 = (@25+@2) */
  for (i=0, rr=w25, cs=w02; i<5; ++i) (*rr++) += (*cs++);
  /* #63: {@18, @0, @1} = vertsplit(@25) */
  casadi_copy(w25, 3, w18);
  w00 = w25[3];
  w01 = w25[4];
  /* #64: (@17[:3] += @18) */
  for (rr=w17+0, cs=w18; rr!=w17+3; rr+=1) *rr += *cs++;
  /* #65: {@11, @15, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @16} = vertsplit(@17) */
  w11 = w17[0];
  w15 = w17[1];
  w03 = w17[2];
  w04 = w17[3];
  w05 = w17[4];
  w06 = w17[5];
  w07 = w17[6];
  w08 = w17[7];
  w09 = w17[8];
  w10 = w17[9];
  w12 = w17[10];
  w13 = w17[11];
  w14 = w17[12];
  w16 = w17[13];
  /* #66: output[1][0] = @11 */
  if (res[1]) res[1][0] = w11;
  /* #67: output[1][1] = @15 */
  if (res[1]) res[1][1] = w15;
  /* #68: output[1][2] = @3 */
  if (res[1]) res[1][2] = w03;
  /* #69: output[1][3] = @4 */
  if (res[1]) res[1][3] = w04;
  /* #70: output[1][4] = @5 */
  if (res[1]) res[1][4] = w05;
  /* #71: output[1][5] = @6 */
  if (res[1]) res[1][5] = w06;
  /* #72: output[1][6] = @7 */
  if (res[1]) res[1][6] = w07;
  /* #73: output[1][7] = @8 */
  if (res[1]) res[1][7] = w08;
  /* #74: @0 = (@0+@9) */
  w00 += w09;
  /* #75: output[1][8] = @0 */
  if (res[1]) res[1][8] = w00;
  /* #76: output[1][9] = @10 */
  if (res[1]) res[1][9] = w10;
  /* #77: output[1][10] = @12 */
  if (res[1]) res[1][10] = w12;
  /* #78: output[1][11] = @13 */
  if (res[1]) res[1][11] = w13;
  /* #79: @1 = (@1+@14) */
  w01 += w14;
  /* #80: output[1][12] = @1 */
  if (res[1]) res[1][12] = w01;
  /* #81: output[1][13] = @16 */
  if (res[1]) res[1][13] = w16;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real morphocopter_model_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 226;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 16*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 226*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
