/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) morphocopter_model_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {124, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

static const casadi_real casadi_zeros[12] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0.};

/* morphocopter_model_cost_ext_cost_e_fun:(i0[14],i1[0],i2[0],i3[124])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, w01, *w02=w+3, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, *w17=w+22, *w18=w+36, *w19=w+39, *w21=w+54, *w22=w+59, *w24=w+171;
  const casadi_real *cs, *ct, *wr20, *wr21, *wr23;
  /* #0: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #1: @1 = 0 */
  w01 = 0.;
  /* #2: @2 = zeros(1x5) */
  casadi_clear(w02, 5);
  /* #3: @3 = input[0][0] */
  w03 = arg[0] ? arg[0][0] : 0;
  /* #4: @4 = input[0][1] */
  w04 = arg[0] ? arg[0][1] : 0;
  /* #5: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #6: @6 = input[0][3] */
  w06 = arg[0] ? arg[0][3] : 0;
  /* #7: @7 = input[0][4] */
  w07 = arg[0] ? arg[0][4] : 0;
  /* #8: @8 = input[0][5] */
  w08 = arg[0] ? arg[0][5] : 0;
  /* #9: @9 = input[0][6] */
  w09 = arg[0] ? arg[0][6] : 0;
  /* #10: @10 = input[0][7] */
  w10 = arg[0] ? arg[0][7] : 0;
  /* #11: @11 = input[0][8] */
  w11 = arg[0] ? arg[0][8] : 0;
  /* #12: @12 = input[0][9] */
  w12 = arg[0] ? arg[0][9] : 0;
  /* #13: @13 = input[0][10] */
  w13 = arg[0] ? arg[0][10] : 0;
  /* #14: @14 = input[0][11] */
  w14 = arg[0] ? arg[0][11] : 0;
  /* #15: @15 = input[0][12] */
  w15 = arg[0] ? arg[0][12] : 0;
  /* #16: @16 = input[0][13] */
  w16 = arg[0] ? arg[0][13] : 0;
  /* #17: @17 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16) */
  rr=w17;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #18: @18 = @17[:3] */
  for (rr=w18, cs=w17+0; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #19: @19 = vertcat(@18, @11, @15) */
  rr=w19;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  *rr++ = w11;
  *rr++ = w15;
  /* #20: @20 = input[3][1] */
  wr20 = arg[3] ? arg[3]+102 : casadi_zeros;
  /* #21: @21 = @20[:5] */
  wr21 = wr20+0;
  /* #22: @19 = (@19-@21) */
  for (i=0, rr=w19, cs=wr21; i<5; ++i) (*rr++) -= (*cs++);
  /* #23: @21 = @19' */
  casadi_copy(w19, 5, w21);
  /* #24: @22 = zeros(10x10) */
  casadi_clear(w22, 100);
  /* #25: @23 = input[3][2] */
  wr23 = arg[3] ? arg[3]+112 : casadi_zeros;
  /* #26: @11 = @23[0] */
  w11 = wr23[0];
  /* #27: (@22[0] = @11) */
  for (rr=w22+0, cs=(&w11); rr!=w22+1; rr+=1) *rr = *cs++;
  /* #28: @11 = @23[1] */
  w11 = wr23[1];
  /* #29: (@22[11] = @11) */
  for (rr=w22+11, cs=(&w11); rr!=w22+12; rr+=1) *rr = *cs++;
  /* #30: @11 = @23[2] */
  w11 = wr23[2];
  /* #31: (@22[22] = @11) */
  for (rr=w22+22, cs=(&w11); rr!=w22+23; rr+=1) *rr = *cs++;
  /* #32: @11 = @23[3] */
  w11 = wr23[3];
  /* #33: (@22[33] = @11) */
  for (rr=w22+33, cs=(&w11); rr!=w22+34; rr+=1) *rr = *cs++;
  /* #34: @11 = @23[4] */
  w11 = wr23[4];
  /* #35: (@22[44] = @11) */
  for (rr=w22+44, cs=(&w11); rr!=w22+45; rr+=1) *rr = *cs++;
  /* #36: @11 = @23[5] */
  w11 = wr23[5];
  /* #37: (@22[55] = @11) */
  for (rr=w22+55, cs=(&w11); rr!=w22+56; rr+=1) *rr = *cs++;
  /* #38: @11 = @23[6] */
  w11 = wr23[6];
  /* #39: (@22[66] = @11) */
  for (rr=w22+66, cs=(&w11); rr!=w22+67; rr+=1) *rr = *cs++;
  /* #40: @11 = @23[7] */
  w11 = wr23[7];
  /* #41: (@22[77] = @11) */
  for (rr=w22+77, cs=(&w11); rr!=w22+78; rr+=1) *rr = *cs++;
  /* #42: @11 = @23[8] */
  w11 = wr23[8];
  /* #43: (@22[88] = @11) */
  for (rr=w22+88, cs=(&w11); rr!=w22+89; rr+=1) *rr = *cs++;
  /* #44: @11 = @23[9] */
  w11 = wr23[9];
  /* #45: (@22[99] = @11) */
  for (rr=w22+99, cs=(&w11); rr!=w22+100; rr+=1) *rr = *cs++;
  /* #46: @11 = @23[10] */
  w11 = wr23[10];
  /* #47: (@22[10] = @11) */
  for (rr=w22+10, cs=(&w11); rr!=w22+11; rr+=1) *rr = *cs++;
  /* #48: @11 = @23[11] */
  w11 = wr23[11];
  /* #49: (@22[1] = @11) */
  for (rr=w22+1, cs=(&w11); rr!=w22+2; rr+=1) *rr = *cs++;
  /* #50: @24 = @22[:50:10;:5] */
  for (rr=w24, cs=w22+0; cs!=w22+50; cs+=10) for (ct=cs+0; ct!=cs+5; ct+=1) *rr++ = *ct;
  /* #51: @2 = mac(@21,@24,@2) */
  for (i=0, rr=w02; i<5; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w21+j, ct=w24+i*5; k<5; ++k) *rr += cs[k*1]**ct++;
  /* #52: @1 = mac(@2,@19,@1) */
  for (i=0, rr=(&w01); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, cs=w02+j, ct=w19+i*5; k<5; ++k) *rr += cs[k*1]**ct++;
  /* #53: @0 = (@0*@1) */
  w00 *= w01;
  /* #54: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real morphocopter_model_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 196;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 196*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
