/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) morphocopter_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_triusolve CASADI_PREFIX(triusolve)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 3, 5, 6, 0, 1,
  2, 1, 2, 2};
static const casadi_int casadi_s3[12] = 
  {3, 3, 0, 1, 3, 6, 0, 0,
  1, 0, 1, 2};
static const casadi_int casadi_s4[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s5[3] = {14, 1, 1};
static const casadi_int casadi_s6[3] = {5, 1, 1};
static const casadi_int casadi_s7[3] = {124, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 9.8066499999999994e+00};
static const casadi_real casadi_c1[3] = {0., 0., 1.};
static const casadi_real casadi_c2[3] = {0., 1., 0.};
static const casadi_real casadi_c3[3] = {1., 0., 0.};

/* morphocopter_model_expl_ode_fun:(i0[14],i1[5],i2[124])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, *w02=w+7, *w03=w+10, w04, w05, w06, *w07=w+22, *w08=w+25, *w09=w+28, *w10=w+31;
  casadi_real *w11=w+40, *w12=w+49, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23;
  const casadi_real *cr, *cs, *ct, *ss;
  /* #0: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = input[0][4] */
  w00 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #4: @0 = input[0][5] */
  w00 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #6: @1 = [0, 0, 9.80665] */
  casadi_copy(casadi_c0, 3, w01);
  /* #7: @2 = zeros(3x1) */
  casadi_clear(w02, 3);
  /* #8: @3 = zeros(3x3) */
  casadi_clear(w03, 9);
  /* #9: @0 = input[0][8] */
  w00 = arg[0] ? arg[0][8] : 0;
  /* #10: @4 = cos(@0) */
  w04 = cos( w00 );
  /* #11: @0 = sin(@0) */
  w00 = sin( w00 );
  /* #12: @5 = (-@0) */
  w05 = (- w00 );
  /* #13: @6 = 0 */
  w06 = 0.;
  /* #14: @7 = horzcat(@4, @5, @6) */
  rr=w07;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  /* #15: @7 = @7' */
  /* #16: @8 = horzcat(@0, @4, @6) */
  rr=w08;
  *rr++ = w00;
  *rr++ = w04;
  *rr++ = w06;
  /* #17: @8 = @8' */
  /* #18: @9 = [[0, 0, 1]] */
  casadi_copy(casadi_c1, 3, w09);
  /* #19: @9 = @9' */
  /* #20: @10 = horzcat(@7, @8, @9) */
  rr=w10;
  for (i=0, cs=w07; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w08; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  /* #21: @11 = @10' */
  for (i=0, rr=w11, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #22: @0 = input[0][7] */
  w00 = arg[0] ? arg[0][7] : 0;
  /* #23: @4 = cos(@0) */
  w04 = cos( w00 );
  /* #24: @0 = sin(@0) */
  w00 = sin( w00 );
  /* #25: @7 = horzcat(@4, @6, @0) */
  rr=w07;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w00;
  /* #26: @7 = @7' */
  /* #27: @8 = [[0, 1, 0]] */
  casadi_copy(casadi_c2, 3, w08);
  /* #28: @8 = @8' */
  /* #29: @0 = (-@0) */
  w00 = (- w00 );
  /* #30: @9 = horzcat(@0, @6, @4) */
  rr=w09;
  *rr++ = w00;
  *rr++ = w06;
  *rr++ = w04;
  /* #31: @9 = @9' */
  /* #32: @10 = horzcat(@7, @8, @9) */
  rr=w10;
  for (i=0, cs=w07; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w08; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  /* #33: @12 = @10' */
  for (i=0, rr=w12, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #34: @10 = mac(@11,@12,@3) */
  casadi_copy(w03, 9, w10);
  for (i=0, rr=w10; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w11+j, ct=w12+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #35: @7 = [[1, 0, 0]] */
  casadi_copy(casadi_c3, 3, w07);
  /* #36: @7 = @7' */
  /* #37: @5 = input[0][6] */
  w05 = arg[0] ? arg[0][6] : 0;
  /* #38: @13 = cos(@5) */
  w13 = cos( w05 );
  /* #39: @5 = sin(@5) */
  w05 = sin( w05 );
  /* #40: @14 = (-@5) */
  w14 = (- w05 );
  /* #41: @8 = horzcat(@6, @13, @14) */
  rr=w08;
  *rr++ = w06;
  *rr++ = w13;
  *rr++ = w14;
  /* #42: @8 = @8' */
  /* #43: @9 = horzcat(@6, @5, @13) */
  rr=w09;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w13;
  /* #44: @9 = @9' */
  /* #45: @11 = horzcat(@7, @8, @9) */
  rr=w11;
  for (i=0, cs=w07; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w08; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w09; i<3; ++i) *rr++ = *cs++;
  /* #46: @12 = @11' */
  for (i=0, rr=w12, cs=w11; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #47: @3 = mac(@10,@12,@3) */
  for (i=0, rr=w03; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w10+j, ct=w12+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #48: @15 = 0.906308 */
  w15 = 9.0630778703664994e-01;
  /* #49: @16 = input[1][0] */
  w16 = arg[1] ? arg[1][0] : 0;
  /* #50: @17 = input[1][1] */
  w17 = arg[1] ? arg[1][1] : 0;
  /* #51: @18 = (@16+@17) */
  w18  = (w16+w17);
  /* #52: @19 = input[1][2] */
  w19 = arg[1] ? arg[1][2] : 0;
  /* #53: @18 = (@18+@19) */
  w18 += w19;
  /* #54: @20 = input[1][3] */
  w20 = arg[1] ? arg[1][3] : 0;
  /* #55: @18 = (@18+@20) */
  w18 += w20;
  /* #56: @18 = (@15*@18) */
  w18  = (w15*w18);
  /* #57: @18 = (-@18) */
  w18 = (- w18 );
  /* #58: @7 = vertcat(@6, @6, @18) */
  rr=w07;
  *rr++ = w06;
  *rr++ = w06;
  *rr++ = w18;
  /* #59: @2 = mac(@3,@7,@2) */
  for (i=0, rr=w02; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w03+j, ct=w07+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #60: @18 = 1.8 */
  w18 = 1.8000000000000000e+00;
  /* #61: @2 = (@2/@18) */
  for (i=0, rr=w02; i<3; ++i) (*rr++) /= w18;
  /* #62: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #63: @18 = @1[0] */
  for (rr=(&w18), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #64: output[0][3] = @18 */
  if (res[0]) res[0][3] = w18;
  /* #65: @18 = @1[1] */
  for (rr=(&w18), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #66: output[0][4] = @18 */
  if (res[0]) res[0][4] = w18;
  /* #67: @18 = @1[2] */
  for (rr=(&w18), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #68: output[0][5] = @18 */
  if (res[0]) res[0][5] = w18;
  /* #69: @18 = input[0][9] */
  w18 = arg[0] ? arg[0][9] : 0;
  /* #70: @21 = input[0][10] */
  w21 = arg[0] ? arg[0][10] : 0;
  /* #71: @22 = input[0][11] */
  w22 = arg[0] ? arg[0][11] : 0;
  /* #72: @1 = vertcat(@18, @21, @22) */
  rr=w01;
  *rr++ = w18;
  *rr++ = w21;
  *rr++ = w22;
  /* #73: @23 = 1 */
  w23 = 1.;
  /* #74: @2 = horzcat(@23, @6, @0) */
  rr=w02;
  *rr++ = w23;
  *rr++ = w06;
  *rr++ = w00;
  /* #75: @2 = @2' */
  /* #76: @5 = (@4*@5) */
  w05  = (w04*w05);
  /* #77: @7 = horzcat(@6, @13, @5) */
  rr=w07;
  *rr++ = w06;
  *rr++ = w13;
  *rr++ = w05;
  /* #78: @7 = @7' */
  /* #79: @13 = (@13*@4) */
  w13 *= w04;
  /* #80: @8 = horzcat(@6, @14, @13) */
  rr=w08;
  *rr++ = w06;
  *rr++ = w14;
  *rr++ = w13;
  /* #81: @8 = @8' */
  /* #82: @3 = horzcat(@2, @7, @8) */
  rr=w03;
  for (i=0, cs=w02; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w07; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w08; i<3; ++i) *rr++ = *cs++;
  /* #83: @10 = @3' */
  for (i=0, rr=w10, cs=w03; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #84: @2 = (@10\@1) */
  rr = w02;
  ss = w10;
  casadi_copy(w01, 3, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #85: @6 = @2[0] */
  for (rr=(&w06), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #86: output[0][6] = @6 */
  if (res[0]) res[0][6] = w06;
  /* #87: @6 = @2[1] */
  for (rr=(&w06), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #88: output[0][7] = @6 */
  if (res[0]) res[0][7] = w06;
  /* #89: @6 = @2[2] */
  for (rr=(&w06), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #90: output[0][8] = @6 */
  if (res[0]) res[0][8] = w06;
  /* #91: @6 = (@17-@16) */
  w06  = (w17-w16);
  /* #92: @6 = (@6+@19) */
  w06 += w19;
  /* #93: @6 = (@6-@20) */
  w06 -= w20;
  /* #94: @14 = 0.206638 */
  w14 = 2.0663817544435620e-01;
  /* #95: @13 = 0.785398 */
  w13 = 7.8539816339744828e-01;
  /* #96: @4 = input[0][12] */
  w04 = arg[0] ? arg[0][12] : 0;
  /* #97: @5 = 2 */
  w05 = 2.;
  /* #98: @4 = (@4/@5) */
  w04 /= w05;
  /* #99: @13 = (@13-@4) */
  w13 -= w04;
  /* #100: @4 = sin(@13) */
  w04 = sin( w13 );
  /* #101: @5 = (@14*@4) */
  w05  = (w14*w04);
  /* #102: @23 = 0.023244 */
  w23 = 2.3244004395738468e-02;
  /* #103: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #104: @0 = (@23*@13) */
  w00  = (w23*w13);
  /* #105: @5 = (@5+@0) */
  w05 += w00;
  /* #106: @6 = (@6*@5) */
  w06 *= w05;
  /* #107: @5 = (@16-@17) */
  w05  = (w16-w17);
  /* #108: @5 = (@5+@19) */
  w05 += w19;
  /* #109: @5 = (@5-@20) */
  w05 -= w20;
  /* #110: @14 = (@14*@13) */
  w14 *= w13;
  /* #111: @23 = (@23*@4) */
  w23 *= w04;
  /* #112: @14 = (@14+@23) */
  w14 += w23;
  /* #113: @5 = (@5*@14) */
  w05 *= w14;
  /* #114: @14 = 0.055 */
  w14 = 5.5000000000000000e-02;
  /* #115: @16 = (-@16) */
  w16 = (- w16 );
  /* #116: @16 = (@16-@17) */
  w16 -= w17;
  /* #117: @16 = (@16+@19) */
  w16 += w19;
  /* #118: @16 = (@16+@20) */
  w16 += w20;
  /* #119: @14 = (@14*@16) */
  w14 *= w16;
  /* #120: @15 = (@15*@14) */
  w15 *= w14;
  /* #121: @2 = vertcat(@6, @5, @15) */
  rr=w02;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w15;
  /* #122: @6 = 0.007247 */
  w06 = 7.2470000000000000e-03;
  /* #123: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #124: @5 = (@6*@4) */
  w05  = (w06*w04);
  /* #125: @15 = 0.0001625 */
  w15 = 1.6250000000000002e-04;
  /* #126: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #127: @14 = (@15*@13) */
  w14  = (w15*w13);
  /* #128: @5 = (@5+@14) */
  w05 += w14;
  /* #129: @14 = 0.0108659 */
  w14 = 1.0865900000000000e-02;
  /* #130: @16 = (@14*@4) */
  w16  = (w14*w04);
  /* #131: @5 = (@5+@16) */
  w05 += w16;
  /* #132: @16 = 0.0027081 */
  w16 = 2.7081000000000002e-03;
  /* #133: @20 = (@16*@13) */
  w20  = (w16*w13);
  /* #134: @5 = (@5+@20) */
  w05 += w20;
  /* #135: @6 = (@6*@13) */
  w06 *= w13;
  /* #136: @15 = (@15*@4) */
  w15 *= w04;
  /* #137: @6 = (@6+@15) */
  w06 += w15;
  /* #138: @14 = (@14*@13) */
  w14 *= w13;
  /* #139: @6 = (@6+@14) */
  w06 += w14;
  /* #140: @16 = (@16*@4) */
  w16 *= w04;
  /* #141: @6 = (@6+@16) */
  w06 += w16;
  /* #142: @16 = 0.0171014 */
  w16 = 1.7101399999999999e-02;
  /* #143: @7 = vertcat(@5, @6, @16) */
  rr=w07;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w16;
  /* #144: @1 = (@7*@1) */
  for (i=0, rr=w01, cr=w07, cs=w01; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #145: @5 = @1[2] */
  for (rr=(&w05), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #146: @6 = (@21*@5) */
  w06  = (w21*w05);
  /* #147: @16 = @1[1] */
  for (rr=(&w16), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #148: @4 = (@22*@16) */
  w04  = (w22*w16);
  /* #149: @6 = (@6-@4) */
  w06 -= w04;
  /* #150: @4 = @1[0] */
  for (rr=(&w04), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #151: @22 = (@22*@4) */
  w22 *= w04;
  /* #152: @5 = (@18*@5) */
  w05  = (w18*w05);
  /* #153: @22 = (@22-@5) */
  w22 -= w05;
  /* #154: @18 = (@18*@16) */
  w18 *= w16;
  /* #155: @21 = (@21*@4) */
  w21 *= w04;
  /* #156: @18 = (@18-@21) */
  w18 -= w21;
  /* #157: @1 = vertcat(@6, @22, @18) */
  rr=w01;
  *rr++ = w06;
  *rr++ = w22;
  *rr++ = w18;
  /* #158: @2 = (@2-@1) */
  for (i=0, rr=w02, cs=w01; i<3; ++i) (*rr++) -= (*cs++);
  /* #159: @7 = sparsity_cast(@7) */
  /* #160: @2 = (@7\@2) */
  casadi_triusolve(casadi_s4, w07, w02, 0, 0, 1);
  /* #161: @6 = @2[0] */
  for (rr=(&w06), cs=w02+0; cs!=w02+1; cs+=1) *rr++ = *cs;
  /* #162: output[0][9] = @6 */
  if (res[0]) res[0][9] = w06;
  /* #163: @6 = @2[1] */
  for (rr=(&w06), cs=w02+1; cs!=w02+2; cs+=1) *rr++ = *cs;
  /* #164: output[0][10] = @6 */
  if (res[0]) res[0][10] = w06;
  /* #165: @6 = @2[2] */
  for (rr=(&w06), cs=w02+2; cs!=w02+3; cs+=1) *rr++ = *cs;
  /* #166: output[0][11] = @6 */
  if (res[0]) res[0][11] = w06;
  /* #167: @6 = input[0][13] */
  w06 = arg[0] ? arg[0][13] : 0;
  /* #168: output[0][12] = @6 */
  if (res[0]) res[0][12] = w06;
  /* #169: @6 = input[1][4] */
  w06 = arg[1] ? arg[1][4] : 0;
  /* #170: @22 = 0.0071648 */
  w22 = 7.1647999999999998e-03;
  /* #171: @6 = (@6/@22) */
  w06 /= w22;
  /* #172: output[0][13] = @6 */
  if (res[0]) res[0][13] = w06;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real morphocopter_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 69;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 69*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
