/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) morphocopter_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_triusolve CASADI_PREFIX(triusolve)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_triusolve(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x, int tr, int unity,
    casadi_int nrhs) {
  casadi_int nrow, ncol, r, c, k, rhs;
  const casadi_int *colind, *row;
  nrow = sp_a[0];
  ncol = sp_a[1];
  colind = sp_a + 2;
  row = colind + ncol + 1;
  for (rhs = 0; rhs < nrhs; ++rhs) {
    if (unity) {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            x[c] += nz_a[k] * x[row[k]];
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            x[row[k]] += nz_a[k] * x[c];
          }
        }
      }
    } else {
      if (tr) {
        for (c = 0; c < ncol; ++c) {
          for (k = colind[c]; k < colind[c+1]; ++k) {
            r = row[k];
            if (r == c) {
              x[c] /= nz_a[k];
            } else {
              x[c] -= nz_a[k] * x[r];
            }
          }
        }
      } else {
        for (c = ncol; c-- > 0; ) {
          for (k = colind[c + 1]; k-- > colind[c]; ) {
            r = row[k];
            if (r == c) {
              x[r] /= nz_a[k];
            } else {
              x[r] -= nz_a[k] * x[c];
            }
          }
        }
      }
    }
    x += nrow;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 3, 5, 6, 0, 1,
  2, 1, 2, 2};
static const casadi_int casadi_s3[12] = 
  {3, 3, 0, 1, 3, 6, 0, 0,
  1, 0, 1, 2};
static const casadi_int casadi_s4[9] = 
  {3, 3, 0, 1, 2, 3, 0, 1,
  2};
static const casadi_int casadi_s5[9] = 
  {1, 3, 0, 1, 2, 3, 0, 0,
  0};
static const casadi_int casadi_s6[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s7[3] = {14, 1, 1};
static const casadi_int casadi_s8[3] = {5, 1, 1};
static const casadi_int casadi_s9[3] = {124, 1, 1};
static const casadi_int casadi_s10[20] = 
  {19, 1, 0, 16, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16, 17, 18};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[3] = {0., 1., 0.};
static const casadi_real casadi_c2[3] = {1., 0., 0.};

static const casadi_real casadi_zeros[14] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* morphocopter_model_expl_vde_adj:(i0[14],i1[14],i2[5],i3[124])->(o0[19x1,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, *w15=w+31, *w16=w+40, *w17=w+43, w18, *w19=w+47, *w20=w+50, w21, *w22=w+54, *w23=w+57;
  casadi_real *w24=w+66, w25, w26, *w27=w+77, w28, w29, w30, w31, w32, w33, *w34=w+86, *w35=w+89;
  casadi_real *w36=w+98, *w37=w+107, w38, *w39=w+117, w40, *w41=w+127, *w42=w+130, w43, w44, w45, w46;
  const casadi_real *cr, *cs, *ct, *ss, *wr00;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14} = vertsplit(@0) */
  w01 = wr00[0];
  w02 = wr00[1];
  w03 = wr00[2];
  w04 = wr00[3];
  w05 = wr00[4];
  w06 = wr00[5];
  w07 = wr00[6];
  w08 = wr00[7];
  w09 = wr00[8];
  w10 = wr00[9];
  w11 = wr00[10];
  w12 = wr00[11];
  w13 = wr00[12];
  w14 = wr00[13];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #5: @3 = input[0][6] */
  w03 = arg[0] ? arg[0][6] : 0;
  /* #6: @2 = cos(@3) */
  w02 = cos( w03 );
  /* #7: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #8: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #9: @17 = @16; (@17[2] += @9) */
  casadi_copy(w16, 3, w17);
  for (rr=w17+2, cs=(&w09); rr!=w17+3; rr+=1) *rr += *cs++;
  /* #10: (@17[1] += @8) */
  for (rr=w17+1, cs=(&w08); rr!=w17+2; rr+=1) *rr += *cs++;
  /* #11: (@17[0] += @7) */
  for (rr=w17+0, cs=(&w07); rr!=w17+1; rr+=1) *rr += *cs++;
  /* #12: @7 = 1 */
  w07 = 1.;
  /* #13: @8 = 0 */
  w08 = 0.;
  /* #14: @9 = input[0][7] */
  w09 = arg[0] ? arg[0][7] : 0;
  /* #15: @1 = sin(@9) */
  w01 = sin( w09 );
  /* #16: @18 = (-@1) */
  w18 = (- w01 );
  /* #17: @19 = horzcat(@7, @8, @18) */
  rr=w19;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w18;
  /* #18: @19 = @19' */
  /* #19: @9 = cos(@9) */
  w09 = cos( w09 );
  /* #20: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #21: @7 = (@9*@3) */
  w07  = (w09*w03);
  /* #22: @20 = horzcat(@8, @2, @7) */
  rr=w20;
  *rr++ = w08;
  *rr++ = w02;
  *rr++ = w07;
  /* #23: @20 = @20' */
  /* #24: @7 = (-@3) */
  w07 = (- w03 );
  /* #25: @21 = (@2*@9) */
  w21  = (w02*w09);
  /* #26: @22 = horzcat(@8, @7, @21) */
  rr=w22;
  *rr++ = w08;
  *rr++ = w07;
  *rr++ = w21;
  /* #27: @22 = @22' */
  /* #28: @23 = horzcat(@19, @20, @22) */
  rr=w23;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #29: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #30: @17 = (@24'\@17) */
  rr = w17;
  ss = w24;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 1, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #31: @21 = input[0][9] */
  w21 = arg[0] ? arg[0][9] : 0;
  /* #32: @25 = input[0][10] */
  w25 = arg[0] ? arg[0][10] : 0;
  /* #33: @26 = input[0][11] */
  w26 = arg[0] ? arg[0][11] : 0;
  /* #34: @19 = vertcat(@21, @25, @26) */
  rr=w19;
  *rr++ = w21;
  *rr++ = w25;
  *rr++ = w26;
  /* #35: @20 = (@24\@19) */
  rr = w20;
  ss = w24;
  casadi_copy(w19, 3, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 1, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #36: @20 = @20' */
  /* #37: @24 = mac(@17,@20,@15) */
  casadi_copy(w15, 9, w24);
  for (i=0, rr=w24; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w17+j, ct=w20+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #38: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<9; ++i) *rr++ = (- *cs++ );
  /* #39: @23 = @24' */
  for (i=0, rr=w23, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #40: {@20, @22, @27} = horzsplit(@23) */
  casadi_copy(w23, 3, w20);
  casadi_copy(w23+3, 3, w22);
  casadi_copy(w23+6, 3, w27);
  /* #41: @27 = @27' */
  /* #42: {NULL, @28, @29} = horzsplit(@27) */
  w28 = w27[1];
  w29 = w27[2];
  /* #43: @28 = (@2*@28) */
  w28  = (w02*w28);
  /* #44: @28 = (-@28) */
  w28 = (- w28 );
  /* #45: @30 = (@9*@29) */
  w30  = (w09*w29);
  /* #46: @30 = (@3*@30) */
  w30  = (w03*w30);
  /* #47: @28 = (@28-@30) */
  w28 -= w30;
  /* #48: @22 = @22' */
  /* #49: {NULL, @30, @31} = horzsplit(@22) */
  w30 = w22[1];
  w31 = w22[2];
  /* #50: @32 = (@9*@31) */
  w32  = (w09*w31);
  /* #51: @32 = (@2*@32) */
  w32  = (w02*w32);
  /* #52: @28 = (@28+@32) */
  w28 += w32;
  /* #53: @30 = (@3*@30) */
  w30  = (w03*w30);
  /* #54: @28 = (@28-@30) */
  w28 -= w30;
  /* #55: @30 = input[0][8] */
  w30 = arg[0] ? arg[0][8] : 0;
  /* #56: @32 = cos(@30) */
  w32 = cos( w30 );
  /* #57: @30 = sin(@30) */
  w30 = sin( w30 );
  /* #58: @33 = (-@30) */
  w33 = (- w30 );
  /* #59: @22 = horzcat(@32, @33, @8) */
  rr=w22;
  *rr++ = w32;
  *rr++ = w33;
  *rr++ = w08;
  /* #60: @22 = @22' */
  /* #61: @27 = horzcat(@30, @32, @8) */
  rr=w27;
  *rr++ = w30;
  *rr++ = w32;
  *rr++ = w08;
  /* #62: @27 = @27' */
  /* #63: @34 = [[0, 0, 1]] */
  casadi_copy(casadi_c0, 3, w34);
  /* #64: @34 = @34' */
  /* #65: @23 = horzcat(@22, @27, @34) */
  rr=w23;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #66: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #67: @22 = horzcat(@9, @8, @1) */
  rr=w22;
  *rr++ = w09;
  *rr++ = w08;
  *rr++ = w01;
  /* #68: @22 = @22' */
  /* #69: @27 = [[0, 1, 0]] */
  casadi_copy(casadi_c1, 3, w27);
  /* #70: @27 = @27' */
  /* #71: @34 = horzcat(@18, @8, @9) */
  rr=w34;
  *rr++ = w18;
  *rr++ = w08;
  *rr++ = w09;
  /* #72: @34 = @34' */
  /* #73: @35 = horzcat(@22, @27, @34) */
  rr=w35;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #74: @36 = @35' */
  for (i=0, rr=w36, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #75: @37 = mac(@24,@36,@15) */
  casadi_copy(w15, 9, w37);
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w24+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #76: @24 = @37' */
  for (i=0, rr=w24, cs=w37; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #77: @18 = 0.555556 */
  w18 = 5.5555555555555558e-01;
  /* #78: @22 = @16; (@22[2] += @6) */
  casadi_copy(w16, 3, w22);
  for (rr=w22+2, cs=(&w06); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #79: (@22[1] += @5) */
  for (rr=w22+1, cs=(&w05); rr!=w22+2; rr+=1) *rr += *cs++;
  /* #80: (@22[0] += @4) */
  for (rr=w22+0, cs=(&w04); rr!=w22+1; rr+=1) *rr += *cs++;
  /* #81: @22 = (@18*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w18*(*cs++));
  /* #82: @18 = 0.906308 */
  w18 = 9.0630778703664994e-01;
  /* #83: @4 = input[2][0] */
  w04 = arg[2] ? arg[2][0] : 0;
  /* #84: @5 = input[2][1] */
  w05 = arg[2] ? arg[2][1] : 0;
  /* #85: @6 = (@4+@5) */
  w06  = (w04+w05);
  /* #86: @33 = input[2][2] */
  w33 = arg[2] ? arg[2][2] : 0;
  /* #87: @6 = (@6+@33) */
  w06 += w33;
  /* #88: @38 = input[2][3] */
  w38 = arg[2] ? arg[2][3] : 0;
  /* #89: @6 = (@6+@38) */
  w06 += w38;
  /* #90: @6 = (@18*@6) */
  w06  = (w18*w06);
  /* #91: @6 = (-@6) */
  w06 = (- w06 );
  /* #92: @27 = vertcat(@8, @8, @6) */
  rr=w27;
  *rr++ = w08;
  *rr++ = w08;
  *rr++ = w06;
  /* #93: @27 = @27' */
  /* #94: @36 = mac(@22,@27,@15) */
  casadi_copy(w15, 9, w36);
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w22+j, ct=w27+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #95: @39 = mac(@24,@36,@15) */
  casadi_copy(w15, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w24+j, ct=w36+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #96: @24 = @39' */
  for (i=0, rr=w24, cs=w39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #97: {NULL, @27, @34} = horzsplit(@24) */
  casadi_copy(w24+3, 3, w27);
  casadi_copy(w24+6, 3, w34);
  /* #98: @34 = @34' */
  /* #99: {NULL, @6, @40} = horzsplit(@34) */
  w06 = w34[1];
  w40 = w34[2];
  /* #100: @40 = (@3*@40) */
  w40  = (w03*w40);
  /* #101: @28 = (@28-@40) */
  w28 -= w40;
  /* #102: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #103: @28 = (@28+@6) */
  w28 += w06;
  /* #104: @27 = @27' */
  /* #105: {NULL, @6, @40} = horzsplit(@27) */
  w06 = w27[1];
  w40 = w27[2];
  /* #106: @40 = (@2*@40) */
  w40  = (w02*w40);
  /* #107: @28 = (@28-@40) */
  w28 -= w40;
  /* #108: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #109: @28 = (@28-@6) */
  w28 -= w06;
  /* #110: output[0][3] = @28 */
  if (res[0]) res[0][3] = w28;
  /* #111: @31 = (@3*@31) */
  w31  = (w03*w31);
  /* #112: @31 = (@1*@31) */
  w31  = (w01*w31);
  /* #113: @31 = (-@31) */
  w31 = (- w31 );
  /* #114: @29 = (@2*@29) */
  w29  = (w02*w29);
  /* #115: @29 = (@1*@29) */
  w29  = (w01*w29);
  /* #116: @31 = (@31-@29) */
  w31 -= w29;
  /* #117: @20 = @20' */
  /* #118: {NULL, NULL, @29} = horzsplit(@20) */
  w29 = w20[2];
  /* #119: @29 = (@9*@29) */
  w29  = (w09*w29);
  /* #120: @31 = (@31-@29) */
  w31 -= w29;
  /* #121: @20 = [[1, 0, 0]] */
  casadi_copy(casadi_c2, 3, w20);
  /* #122: @20 = @20' */
  /* #123: @27 = horzcat(@8, @2, @7) */
  rr=w27;
  *rr++ = w08;
  *rr++ = w02;
  *rr++ = w07;
  /* #124: @27 = @27' */
  /* #125: @34 = horzcat(@8, @3, @2) */
  rr=w34;
  *rr++ = w08;
  *rr++ = w03;
  *rr++ = w02;
  /* #126: @34 = @34' */
  /* #127: @24 = horzcat(@20, @27, @34) */
  rr=w24;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #128: @39 = mac(@36,@24,@15) */
  casadi_copy(w15, 9, w39);
  for (i=0, rr=w39; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w36+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #129: @36 = mac(@23,@39,@15) */
  casadi_copy(w15, 9, w36);
  for (i=0, rr=w36; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w23+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #130: @23 = @36' */
  for (i=0, rr=w23, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #131: {@20, NULL, @27} = horzsplit(@23) */
  casadi_copy(w23, 3, w20);
  casadi_copy(w23+6, 3, w27);
  /* #132: @27 = @27' */
  /* #133: {@8, NULL, @3} = horzsplit(@27) */
  w08 = w27[0];
  w03 = w27[2];
  /* #134: @3 = (@1*@3) */
  w03  = (w01*w03);
  /* #135: @31 = (@31-@3) */
  w31 -= w03;
  /* #136: @8 = (@9*@8) */
  w08  = (w09*w08);
  /* #137: @31 = (@31-@8) */
  w31 -= w08;
  /* #138: @20 = @20' */
  /* #139: {@8, NULL, @3} = horzsplit(@20) */
  w08 = w20[0];
  w03 = w20[2];
  /* #140: @9 = (@9*@3) */
  w09 *= w03;
  /* #141: @31 = (@31+@9) */
  w31 += w09;
  /* #142: @1 = (@1*@8) */
  w01 *= w08;
  /* #143: @31 = (@31-@1) */
  w31 -= w01;
  /* #144: output[0][4] = @31 */
  if (res[0]) res[0][4] = w31;
  /* #145: @23 = mac(@39,@35,@15) */
  casadi_copy(w15, 9, w23);
  for (i=0, rr=w23; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w39+j, ct=w35+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #146: @39 = @23' */
  for (i=0, rr=w39, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #147: {@20, @27, NULL} = horzsplit(@39) */
  casadi_copy(w39, 3, w20);
  casadi_copy(w39+3, 3, w27);
  /* #148: @27 = @27' */
  /* #149: {@31, @1, NULL} = horzsplit(@27) */
  w31 = w27[0];
  w01 = w27[1];
  /* #150: @31 = (@32*@31) */
  w31  = (w32*w31);
  /* #151: @1 = (@30*@1) */
  w01  = (w30*w01);
  /* #152: @31 = (@31-@1) */
  w31 -= w01;
  /* #153: @20 = @20' */
  /* #154: {@1, @8, NULL} = horzsplit(@20) */
  w01 = w20[0];
  w08 = w20[1];
  /* #155: @32 = (@32*@8) */
  w32 *= w08;
  /* #156: @31 = (@31-@32) */
  w31 -= w32;
  /* #157: @30 = (@30*@1) */
  w30 *= w01;
  /* #158: @31 = (@31-@30) */
  w31 -= w30;
  /* #159: output[0][5] = @31 */
  if (res[0]) res[0][5] = w31;
  /* #160: @31 = 0.007247 */
  w31 = 7.2470000000000000e-03;
  /* #161: @30 = 0.785398 */
  w30 = 7.8539816339744828e-01;
  /* #162: @1 = input[0][12] */
  w01 = arg[0] ? arg[0][12] : 0;
  /* #163: @32 = 2 */
  w32 = 2.;
  /* #164: @1 = (@1/@32) */
  w01 /= w32;
  /* #165: @30 = (@30-@1) */
  w30 -= w01;
  /* #166: @1 = sin(@30) */
  w01 = sin( w30 );
  /* #167: @32 = sq(@1) */
  w32 = casadi_sq( w01 );
  /* #168: @8 = (@31*@32) */
  w08  = (w31*w32);
  /* #169: @9 = 0.0001625 */
  w09 = 1.6250000000000002e-04;
  /* #170: @30 = cos(@30) */
  w30 = cos( w30 );
  /* #171: @3 = sq(@30) */
  w03 = casadi_sq( w30 );
  /* #172: @2 = (@9*@3) */
  w02  = (w09*w03);
  /* #173: @8 = (@8+@2) */
  w08 += w02;
  /* #174: @2 = 0.0108659 */
  w02 = 1.0865900000000000e-02;
  /* #175: @7 = (@2*@32) */
  w07  = (w02*w32);
  /* #176: @8 = (@8+@7) */
  w08 += w07;
  /* #177: @7 = 0.0027081 */
  w07 = 2.7081000000000002e-03;
  /* #178: @29 = (@7*@3) */
  w29  = (w07*w03);
  /* #179: @8 = (@8+@29) */
  w08 += w29;
  /* #180: @29 = (@31*@3) */
  w29  = (w31*w03);
  /* #181: @28 = (@9*@32) */
  w28  = (w09*w32);
  /* #182: @29 = (@29+@28) */
  w29 += w28;
  /* #183: @3 = (@2*@3) */
  w03  = (w02*w03);
  /* #184: @29 = (@29+@3) */
  w29 += w03;
  /* #185: @32 = (@7*@32) */
  w32  = (w07*w32);
  /* #186: @29 = (@29+@32) */
  w29 += w32;
  /* #187: @32 = 0.0171014 */
  w32 = 1.7101399999999999e-02;
  /* #188: @20 = vertcat(@8, @29, @32) */
  rr=w20;
  *rr++ = w08;
  *rr++ = w29;
  *rr++ = w32;
  /* #189: @27 = (@20*@19) */
  for (i=0, rr=w27, cr=w20, cs=w19; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #190: @8 = @27[1] */
  for (rr=(&w08), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #191: @34 = @16; (@34[2] += @12) */
  casadi_copy(w16, 3, w34);
  for (rr=w34+2, cs=(&w12); rr!=w34+3; rr+=1) *rr += *cs++;
  /* #192: (@34[1] += @11) */
  for (rr=w34+1, cs=(&w11); rr!=w34+2; rr+=1) *rr += *cs++;
  /* #193: (@34[0] += @10) */
  for (rr=w34+0, cs=(&w10); rr!=w34+1; rr+=1) *rr += *cs++;
  /* #194: @41 = sparsity_cast(@20) */
  casadi_copy(w20, 3, w41);
  /* #195: @34 = (@41'\@34) */
  casadi_triusolve(casadi_s4, w41, w34, 1, 0, 1);
  /* #196: @42 = (-@34) */
  for (i=0, rr=w42, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #197: {@10, @11, @12} = vertsplit(@42) */
  w10 = w42[0];
  w11 = w42[1];
  w12 = w42[2];
  /* #198: @29 = (@8*@12) */
  w29  = (w08*w12);
  /* #199: @32 = @27[2] */
  for (rr=(&w32), cs=w27+2; cs!=w27+3; cs+=1) *rr++ = *cs;
  /* #200: @3 = (@32*@11) */
  w03  = (w32*w11);
  /* #201: @29 = (@29-@3) */
  w29 -= w03;
  /* #202: @3 = (@26*@11) */
  w03  = (w26*w11);
  /* #203: @28 = (@25*@12) */
  w28  = (w25*w12);
  /* #204: @3 = (@3-@28) */
  w03 -= w28;
  /* #205: @42 = @16; (@42[0] += @3) */
  casadi_copy(w16, 3, w42);
  for (rr=w42+0, cs=(&w03); rr!=w42+1; rr+=1) *rr += *cs++;
  /* #206: @3 = (@21*@12) */
  w03  = (w21*w12);
  /* #207: @28 = (@26*@10) */
  w28  = (w26*w10);
  /* #208: @3 = (@3-@28) */
  w03 -= w28;
  /* #209: (@42[1] += @3) */
  for (rr=w42+1, cs=(&w03); rr!=w42+2; rr+=1) *rr += *cs++;
  /* #210: @3 = (@25*@10) */
  w03  = (w25*w10);
  /* #211: @28 = (@21*@11) */
  w28  = (w21*w11);
  /* #212: @3 = (@3-@28) */
  w03 -= w28;
  /* #213: (@42[2] += @3) */
  for (rr=w42+2, cs=(&w03); rr!=w42+3; rr+=1) *rr += *cs++;
  /* #214: @20 = (@20*@42) */
  for (i=0, rr=w20, cs=w42; i<3; ++i) (*rr++) *= (*cs++);
  /* #215: {@3, @28, @6} = vertsplit(@20) */
  w03 = w20[0];
  w28 = w20[1];
  w06 = w20[2];
  /* #216: @29 = (@29+@3) */
  w29 += w03;
  /* #217: {@3, @40, @43} = vertsplit(@17) */
  w03 = w17[0];
  w40 = w17[1];
  w43 = w17[2];
  /* #218: @29 = (@29+@3) */
  w29 += w03;
  /* #219: output[0][6] = @29 */
  if (res[0]) res[0][6] = w29;
  /* #220: @29 = (@32*@10) */
  w29  = (w32*w10);
  /* #221: @3 = @27[0] */
  for (rr=(&w03), cs=w27+0; cs!=w27+1; cs+=1) *rr++ = *cs;
  /* #222: @12 = (@3*@12) */
  w12  = (w03*w12);
  /* #223: @29 = (@29-@12) */
  w29 -= w12;
  /* #224: @29 = (@29+@28) */
  w29 += w28;
  /* #225: @29 = (@29+@40) */
  w29 += w40;
  /* #226: output[0][7] = @29 */
  if (res[0]) res[0][7] = w29;
  /* #227: @11 = (@3*@11) */
  w11  = (w03*w11);
  /* #228: @10 = (@8*@10) */
  w10  = (w08*w10);
  /* #229: @11 = (@11-@10) */
  w11 -= w10;
  /* #230: @11 = (@11+@6) */
  w11 += w06;
  /* #231: @11 = (@11+@43) */
  w11 += w43;
  /* #232: output[0][8] = @11 */
  if (res[0]) res[0][8] = w11;
  /* #233: @11 = 0.5 */
  w11 = 5.0000000000000000e-01;
  /* #234: @43 = (2.*@30) */
  w43 = (2.* w30 );
  /* #235: @27 = zeros(3x3,3nz) */
  casadi_clear(w27, 3);
  /* #236: @6 = (@5-@4) */
  w06  = (w05-w04);
  /* #237: @6 = (@6+@33) */
  w06 += w33;
  /* #238: @6 = (@6-@38) */
  w06 -= w38;
  /* #239: @10 = 0.206638 */
  w10 = 2.0663817544435620e-01;
  /* #240: @29 = (@10*@1) */
  w29  = (w10*w01);
  /* #241: @40 = 0.023244 */
  w40 = 2.3244004395738468e-02;
  /* #242: @28 = (@40*@30) */
  w28  = (w40*w30);
  /* #243: @29 = (@29+@28) */
  w29 += w28;
  /* #244: @28 = (@6*@29) */
  w28  = (w06*w29);
  /* #245: @12 = (@4-@5) */
  w12  = (w04-w05);
  /* #246: @12 = (@12+@33) */
  w12 += w33;
  /* #247: @12 = (@12-@38) */
  w12 -= w38;
  /* #248: @44 = (@10*@30) */
  w44  = (w10*w30);
  /* #249: @45 = (@40*@1) */
  w45  = (w40*w01);
  /* #250: @44 = (@44+@45) */
  w44 += w45;
  /* #251: @45 = (@12*@44) */
  w45  = (w12*w44);
  /* #252: @46 = 0.055 */
  w46 = 5.5000000000000000e-02;
  /* #253: @4 = (-@4) */
  w04 = (- w04 );
  /* #254: @4 = (@4-@5) */
  w04 -= w05;
  /* #255: @4 = (@4+@33) */
  w04 += w33;
  /* #256: @4 = (@4+@38) */
  w04 += w38;
  /* #257: @4 = (@46*@4) */
  w04  = (w46*w04);
  /* #258: @4 = (@18*@4) */
  w04  = (w18*w04);
  /* #259: @17 = vertcat(@28, @45, @4) */
  rr=w17;
  *rr++ = w28;
  *rr++ = w45;
  *rr++ = w04;
  /* #260: @28 = (@25*@32) */
  w28  = (w25*w32);
  /* #261: @45 = (@26*@8) */
  w45  = (w26*w08);
  /* #262: @28 = (@28-@45) */
  w28 -= w45;
  /* #263: @26 = (@26*@3) */
  w26 *= w03;
  /* #264: @32 = (@21*@32) */
  w32  = (w21*w32);
  /* #265: @26 = (@26-@32) */
  w26 -= w32;
  /* #266: @21 = (@21*@8) */
  w21 *= w08;
  /* #267: @25 = (@25*@3) */
  w25 *= w03;
  /* #268: @21 = (@21-@25) */
  w21 -= w25;
  /* #269: @20 = vertcat(@28, @26, @21) */
  rr=w20;
  *rr++ = w28;
  *rr++ = w26;
  *rr++ = w21;
  /* #270: @17 = (@17-@20) */
  for (i=0, rr=w17, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #271: @17 = (@41\@17) */
  casadi_triusolve(casadi_s4, w41, w17, 0, 0, 1);
  /* #272: @17 = @17' */
  /* #273: @27 = mac(@34,@17,@27) */
  casadi_mtimes(w34, casadi_s6, w17, casadi_s5, w27, casadi_s4, w, 0);
  /* #274: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<3; ++i) *rr++ = (- *cs++ );
  /* #275: @27 = nonzeros(@27) */
  /* #276: @19 = (@19*@42) */
  for (i=0, rr=w19, cs=w42; i<3; ++i) (*rr++) *= (*cs++);
  /* #277: @27 = (@27+@19) */
  for (i=0, rr=w27, cs=w19; i<3; ++i) (*rr++) += (*cs++);
  /* #278: {@28, @26, NULL} = vertsplit(@27) */
  w28 = w27[0];
  w26 = w27[1];
  /* #279: @21 = (@2*@26) */
  w21  = (w02*w26);
  /* #280: @21 = (@43*@21) */
  w21  = (w43*w21);
  /* #281: @25 = (@31*@26) */
  w25  = (w31*w26);
  /* #282: @25 = (@43*@25) */
  w25  = (w43*w25);
  /* #283: @21 = (@21+@25) */
  w21 += w25;
  /* #284: @25 = (@7*@28) */
  w25  = (w07*w28);
  /* #285: @25 = (@43*@25) */
  w25  = (w43*w25);
  /* #286: @21 = (@21+@25) */
  w21 += w25;
  /* #287: @25 = (@9*@28) */
  w25  = (w09*w28);
  /* #288: @43 = (@43*@25) */
  w43 *= w25;
  /* #289: @21 = (@21+@43) */
  w21 += w43;
  /* #290: {@43, @25, @3} = vertsplit(@34) */
  w43 = w34[0];
  w25 = w34[1];
  w03 = w34[2];
  /* #291: @12 = (@12*@25) */
  w12 *= w25;
  /* #292: @8 = (@10*@12) */
  w08  = (w10*w12);
  /* #293: @21 = (@21+@8) */
  w21 += w08;
  /* #294: @6 = (@6*@43) */
  w06 *= w43;
  /* #295: @8 = (@40*@6) */
  w08  = (w40*w06);
  /* #296: @21 = (@21+@8) */
  w21 += w08;
  /* #297: @21 = (@1*@21) */
  w21  = (w01*w21);
  /* #298: @21 = (@11*@21) */
  w21  = (w11*w21);
  /* #299: @1 = (2.*@1) */
  w01 = (2.* w01 );
  /* #300: @7 = (@7*@26) */
  w07 *= w26;
  /* #301: @7 = (@1*@7) */
  w07  = (w01*w07);
  /* #302: @9 = (@9*@26) */
  w09 *= w26;
  /* #303: @9 = (@1*@9) */
  w09  = (w01*w09);
  /* #304: @7 = (@7+@9) */
  w07 += w09;
  /* #305: @2 = (@2*@28) */
  w02 *= w28;
  /* #306: @2 = (@1*@2) */
  w02  = (w01*w02);
  /* #307: @7 = (@7+@2) */
  w07 += w02;
  /* #308: @31 = (@31*@28) */
  w31 *= w28;
  /* #309: @1 = (@1*@31) */
  w01 *= w31;
  /* #310: @7 = (@7+@1) */
  w07 += w01;
  /* #311: @40 = (@40*@12) */
  w40 *= w12;
  /* #312: @7 = (@7+@40) */
  w07 += w40;
  /* #313: @10 = (@10*@6) */
  w10 *= w06;
  /* #314: @7 = (@7+@10) */
  w07 += w10;
  /* #315: @30 = (@30*@7) */
  w30 *= w07;
  /* #316: @11 = (@11*@30) */
  w11 *= w30;
  /* #317: @21 = (@21-@11) */
  w21 -= w11;
  /* #318: output[0][9] = @21 */
  if (res[0]) res[0][9] = w21;
  /* #319: output[0][10] = @13 */
  if (res[0]) res[0][10] = w13;
  /* #320: @44 = (@44*@25) */
  w44 *= w25;
  /* #321: @3 = (@18*@3) */
  w03  = (w18*w03);
  /* #322: @46 = (@46*@3) */
  w46 *= w03;
  /* #323: @3 = (@44-@46) */
  w03  = (w44-w46);
  /* #324: @29 = (@29*@43) */
  w29 *= w43;
  /* #325: @3 = (@3-@29) */
  w03 -= w29;
  /* #326: @39 = @24' */
  for (i=0, rr=w39, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #327: @15 = mac(@37,@39,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w37+j, ct=w39+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #328: @37 = @15' */
  for (i=0, rr=w37, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #329: @16 = mac(@37,@22,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w37+j, ct=w22+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #330: {NULL, NULL, @43} = vertsplit(@16) */
  w43 = w16[2];
  /* #331: @18 = (@18*@43) */
  w18 *= w43;
  /* #332: @3 = (@3-@18) */
  w03 -= w18;
  /* #333: output[0][11] = @3 */
  if (res[0]) res[0][11] = w03;
  /* #334: @3 = (-@44) */
  w03 = (- w44 );
  /* #335: @3 = (@3-@46) */
  w03 -= w46;
  /* #336: @3 = (@3+@29) */
  w03 += w29;
  /* #337: @3 = (@3-@18) */
  w03 -= w18;
  /* #338: output[0][12] = @3 */
  if (res[0]) res[0][12] = w03;
  /* #339: @3 = (@46+@44) */
  w03  = (w46+w44);
  /* #340: @3 = (@3+@29) */
  w03 += w29;
  /* #341: @3 = (@3-@18) */
  w03 -= w18;
  /* #342: output[0][13] = @3 */
  if (res[0]) res[0][13] = w03;
  /* #343: @46 = (@46-@44) */
  w46 -= w44;
  /* #344: @46 = (@46-@29) */
  w46 -= w29;
  /* #345: @46 = (@46-@18) */
  w46 -= w18;
  /* #346: output[0][14] = @46 */
  if (res[0]) res[0][14] = w46;
  /* #347: @46 = 139.571 */
  w46 = 1.3957123715944618e+02;
  /* #348: @46 = (@46*@14) */
  w46 *= w14;
  /* #349: output[0][15] = @46 */
  if (res[0]) res[0][15] = w46;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void morphocopter_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void morphocopter_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int morphocopter_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real morphocopter_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* morphocopter_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* morphocopter_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 137;
  return 0;
}

CASADI_SYMBOL_EXPORT int morphocopter_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 15*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 137*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
